from PySide2 import QtCore, QtGui, QtWidgets


class UIProfileWindow(object):
    def setupUi(self, profile_window):
        profile_window.setObjectName("Profile Window")
        profile_window.resize(350, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(profile_window.sizePolicy().hasHeightForWidth())
        profile_window.setSizePolicy(sizePolicy)
        profile_window.setMinimumSize(QtCore.QSize(350, 180))
        profile_window.setMaximumSize(QtCore.QSize(350, 180))
        self.formLayoutWidget = QtWidgets.QWidget(profile_window)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.username_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.username_edit.setMaxLength(20)
        self.username_edit.setObjectName("username_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_edit)
        self.password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_edit.setObjectName("password_edit")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_edit)
        self.pu_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.pu_label.setObjectName("pu_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pu_label)
        self.pu_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pu_edit.setMaxLength(14)
        self.pu_edit.setObjectName("pu_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pu_edit)
        self.secret_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.secret_label.setObjectName("secret_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.secret_label)
        self.secret_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.secret_edit.setMaxLength(27)
        self.secret_edit.setObjectName("secret_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.secret_edit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(profile_window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 330, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.confirm_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.confirm_btn.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.confirm_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_btn.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.cancel_btn)

        self.retranslateUi(profile_window)
        QtCore.QMetaObject.connectSlotsByName(profile_window)

        self.cancel_btn.setDefault(True)
        self.cancel_btn.clicked.connect(lambda: profile_window.close())

    def retranslateUi(self, ProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileWindow.setWindowTitle(_translate("ProfileWindow", "Dialog"))
        self.username_label.setText(_translate("ProfileWindow", "Username:"))
        self.password_label.setText(_translate("ProfileWindow", "Password:"))
        self.pu_label.setText(_translate("ProfileWindow", "PU Script:"))
        self.secret_label.setText(_translate("ProfileWindow", "Secret:"))
        self.confirm_btn.setText(_translate("ProfileWindow", "Confirm"))
        self.cancel_btn.setText(_translate("ProfileWindow", "Cancel"))

